import { readFileSync, writeFileSync } from "node:fs";
import { APCAcontrast, sRGBtoY } from "apca-w3";
import { converter, wcagContrast } from "culori";

const rgb = converter("rgb");
const hues = { neutral: 260, note: 300, info: 250, warning: 55, danger: 25, success: 155 };
const contrastTargets = {
    light: [null, null, null, null, null, 25, 40, 60, 80, 86, 92, 100],
    dark: [null, null, null, null, null, 20, 35, 50, 65, 72, 85, 95]
};
const semanticChroma = {
    light: [.002, .005, .012, .02, .03, .045, .065, .085, .10, .086704, .07, .035],
    dark: [.002, .006, .018, .035, .06, .10, .15, .20, .24, .21, .15, .08]
};
const neutralChroma = [.004, .007, .01, .014, .018, .022, .026, .028, .026, .024, .018, .012];
const surfaces = { light: [.985, .97, .95, .925, .88], dark: [.19, .22, .25, .28, .33] };
const path = new URL("../src/05-palette.css", import.meta.url);
const reportPath = new URL("../palette.json", import.meta.url);
const check = process.argv.includes("--check");

const channels = color => {
    const value = rgb(color);
    return [value.r, value.g, value.b].map(channel => channel * 255);
};

const luminance = color => sRGBtoY(channels(color).map(channel => Math.max(0, Math.min(255, channel))));
const contrast = (text, background) => APCAcontrast(luminance(text), luminance(background));
const inGamut = color => channels(color).every(channel => channel >= 0 && channel <= 255);
const round = value => Number(value.toFixed(6));
const format = color => `oklch(${color.l} ${color.c} ${color.h})`;
const rows = [];
const report = { method: "APCA 0.0.98G / apca-w3 0.1.9", reference: "Each tone's level 1", palettes: {} };

for (const mode of ["light", "dark"]) {
    const targets = contrastTargets[mode];
    const palettes = {};
    for (const [tone, hue] of Object.entries(hues)) {
        palettes[tone] = [{ mode: "oklch", l: surfaces[mode][0], c: semanticChroma[mode][0], h: hue }];
    }

    for (let index = 1; index < 12; index++) {
        const solve = (hue, c, background) => {
            if (index < 5) return { mode: "oklch", l: surfaces[mode][index], c: round(c), h: hue };
            let low = .02;
            let high = .999;
            for (let iteration = 0; iteration < 48; iteration++) {
                const l = (low + high) / 2;
                const lc = Math.abs(contrast({ mode: "oklch", l, c, h: hue }, background));
                if ((lc > targets[index]) === (mode === "light")) low = l;
                else high = l;
            }
            return { mode: "oklch", l: round((low + high) / 2), c: round(c), h: hue };
        };

        let sharedChroma = Math.min(semanticChroma[mode][index], .12);
        while (Object.entries(hues).filter(([tone]) => tone !== "neutral").some(([tone, hue]) =>
            !inGamut(solve(hue, sharedChroma, palettes[tone][0])))) sharedChroma *= .97;
        for (const [tone, hue] of Object.entries(hues)) {
            // Match semantic chroma and contrast within each mode.
            let c = tone === "neutral" ? neutralChroma[index] : sharedChroma;
            while (!inGamut(solve(hue, c, palettes[tone][0]))) {
                c *= .97;
                if (c < .0001) throw new Error("Unable to fit palette in sRGB");
            }
            const color = solve(hue, c, palettes[tone][0]);
            palettes[tone].push({ ...color, l: round(color.l), c: round(color.c) });
        }
    }

    report.palettes[mode] = {};
    for (const [tone, colors] of Object.entries(palettes)) {
        report.palettes[mode][tone] = colors.map((color, index) => {
            const lc = contrast(color, colors[0]);
            if (!inGamut(color)) throw new Error(`Out of gamut: ${mode}/${tone}/${index + 1}`);
            if (targets[index] && Math.abs(Math.abs(lc) - targets[index]) > .1) {
                throw new Error(`Contrast target missed: ${mode}/${tone}/${index + 1}`);
            }
            rows.push(`        --palette-${mode}-${tone}-${index + 1}: ${format(color)};`);
            return { css: format(color), apca: Number(lc.toFixed(2)), wcag2: Number(wcagContrast(color, colors[0]).toFixed(2)) };
        });
        rows.push("");
    }
}

const css = `/*!
 * This material is licensed under the terms of the MIT License.
 * A copy of the license is available at https://github.com/tanguylegazon/custom-css/blob/main/LICENSE.
 */

/* Generated by scripts/palette.mjs. */
@layer theme {
    :root {
${rows.join("\n").trimEnd()}
    }
}
`;
const json = JSON.stringify(report, null, 4) + "\n";

for (const [file, expected] of [[path, css], [reportPath, json]]) {
    if (check) {
        if (readFileSync(file, "utf8").replace(/\r\n/g, "\n") !== expected) throw new Error(`Stale generated file: ${file}`);
    } else {
        writeFileSync(file, expected);
    }
}
console.log("Palette " + (check ? "verified" : "generated") + ": 6 tones, 12 levels, 2 modes; APCA target tolerance 0.1 Lc.");
