name: Deploy for distribution

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'src/*.css'

permissions:
  contents: write

jobs:
  distribute:
    runs-on: ubuntu-latest
    timeout-minutes: 3

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Install Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 'latest'

      - name: Build CSS files
        run: |
          cat src/*.css > custom.css
          npx csso-cli -i "custom.css" -o "custom.min.css" --comments first-exclamation

      - name: Push to distribution branch
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git checkout --orphan dist
          git reset
          git add custom.css
          git add custom.min.css
          git commit -m "[bot] Build CSS files"
          git push --force origin dist
