name: Deploy for distribution

on:
  workflow_dispatch:
  push:
    paths:
      - 'custom.css'

permissions:
  contents: write

jobs:
  minify:
    runs-on: ubuntu-latest
    timeout-minutes: 3

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 'latest'

      - name: Minify CSS files
        run: npx csso-cli -i "custom.css" -o "custom.min.css" --comments first-exclamation

      - name: Push to distribution branch
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git checkout --orphan dist
          git reset
          git add custom.min.css
          git commit -m "[bot] Minify CSS file"
          git push --force origin dist