name: Minify CSS

on:
  workflow_dispatch:
  push:
    paths:
      - 'custom.css'
      - '!**/*.min.css'

permissions:
  contents: write

jobs:
  minify:
    runs-on: ubuntu-latest
    timeout-minutes: 3

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Minify CSS files
        run: npx csso-cli -i "custom.css" -o "custom.min.css" --comments first-exclamation

      - name: Push to build branch
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git checkout --orphan dist
          git reset
          git add custom.min.css
          git commit -m "Minify CSS [skip ci]"
          git push --force origin dist