name: Minify CSS

on:
  workflow_dispatch:
  push:
    paths:
      - 'custom.css'
      - '!**/*.min.css'

jobs:
  minify:
    runs-on: ubuntu-latest
    timeout-minutes: 3

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Minify CSS Files
        run: npx csso-cli -i "custom.css" -o "custom.min.css" --comments first-exclamation && ls

      - name: Commit minified file
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          if [ "$(git status --porcelain)" ]; then
            git add .
            git commit -m "Minify CSS [skip ci]"
            git push
          fi